create table if not exists public.export_diagnostics (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  quotation_id uuid null,
  created_at timestamptz not null default now(),
  export_kind text not null check (export_kind in ('image','pdf')),
  stage text not null,
  success boolean not null default false,
  error_message text,
  user_agent text,
  viewport_width integer,
  viewport_height integer,
  page_count integer,
  details jsonb not null default '{}'::jsonb
);

alter table public.export_diagnostics enable row level security;

drop policy if exists "Owners insert export diagnostics" on public.export_diagnostics;
create policy "Owners insert export diagnostics" on public.export_diagnostics
for insert to authenticated with check ((select auth.uid()) = owner_id);

drop policy if exists "Owners select export diagnostics" on public.export_diagnostics;
create policy "Owners select export diagnostics" on public.export_diagnostics
for select to authenticated using ((select auth.uid()) = owner_id);

drop policy if exists "Owners delete export diagnostics" on public.export_diagnostics;
create policy "Owners delete export diagnostics" on public.export_diagnostics
for delete to authenticated using ((select auth.uid()) = owner_id);

grant select, insert, delete on public.export_diagnostics to authenticated;
grant usage, select on sequence public.export_diagnostics_id_seq to authenticated;
create index if not exists export_diagnostics_owner_created_idx on public.export_diagnostics(owner_id, created_at desc);
