import { useState, type FormEvent } from 'react'
import { MapPin, Plus, X } from 'lucide-react'
import type { ClientRecord } from '../../db/repositories'
import { clientSchema, type ClientDraft } from './clientSchema'

const empty: ClientDraft = { name: '', phone: '', email: '', address: '', locations: [{ label: '', address: '' }] }
export function ClientForm({ initialValue, onSave, onCancel }: { initialValue?: ClientRecord; onSave: (value: ClientRecord) => void | Promise<void>; onCancel: () => void }) {
  const [value, setValue] = useState<ClientDraft>(initialValue ? { ...initialValue.client, locations: initialValue.locations.map(({ label, address }) => ({ label, address })) } : empty)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const input = (name: keyof Omit<ClientDraft, 'locations'>) => ({ value: value[name], onChange: (event: React.ChangeEvent<HTMLInputElement>) => setValue((current) => ({ ...current, [name]: event.target.value })) })
  const setLocation = (index: number, name: 'label' | 'address', text: string) => setValue((current) => ({ ...current, locations: current.locations.map((item, itemIndex) => itemIndex === index ? { ...item, [name]: text } : item) }))
  const submit = async (event: FormEvent) => { event.preventDefault(); const result = clientSchema.safeParse(value); if (!result.success) { setErrors(Object.fromEntries(result.error.issues.map((issue) => [String(issue.path[0]), issue.message]))); return } const now = new Date().toISOString(); const clientId = initialValue?.client.id ?? crypto.randomUUID(); await onSave({ client: { id: clientId, name: result.data.name, phone: result.data.phone, email: result.data.email, address: result.data.address, updatedAt: now }, locations: result.data.locations.filter((item) => item.label || item.address).map((item, index) => ({ id: initialValue?.locations[index]?.id ?? crypto.randomUUID(), clientId, ...item, updatedAt: now })) }) }
  return <form className="form-card client-form" onSubmit={submit} noValidate><header className="form-title"><div><h1>{initialValue ? 'Editar cliente' : 'Nuevo cliente'}</h1><p>Contacto y lugares donde realizas sus proyectos.</p></div><button className="icon-button" type="button" onClick={onCancel} aria-label="Cerrar formulario"><X aria-hidden="true"/></button></header>
    <fieldset><legend className="sr-only">Datos de contacto</legend><div className="form-field"><label htmlFor="client-name">Nombre del cliente</label><input id="client-name" {...input('name')} aria-invalid={Boolean(errors.name)} aria-describedby={errors.name ? 'client-name-error' : undefined}/>{errors.name && <span id="client-name-error" className="field-error">{errors.name}</span>}</div><label>Teléfono<input type="tel" {...input('phone')}/></label><div className="form-field"><label htmlFor="client-email">Correo electrónico</label><input id="client-email" type="email" {...input('email')} aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? 'client-email-error' : undefined}/>{errors.email && <span id="client-email-error" className="field-error">{errors.email}</span>}</div><label>Dirección de contacto<input {...input('address')}/></label></fieldset>
    <fieldset><legend>Ubicaciones de proyectos</legend>{value.locations.map((item, index) => <div className="location-fields" key={index}><MapPin aria-hidden="true"/><label>Nombre de ubicación {index + 1}<input value={item.label} onChange={(event) => setLocation(index, 'label', event.target.value)}/></label><label>Dirección de ubicación {index + 1}<input value={item.address} onChange={(event) => setLocation(index, 'address', event.target.value)}/></label></div>)}<button className="button button--quiet" type="button" onClick={() => setValue((current) => ({ ...current, locations: [...current.locations, { label: '', address: '' }] }))}><Plus aria-hidden="true"/>Agregar otra ubicación</button></fieldset><button className="button button--primary" type="submit">Guardar cliente</button>
  </form>
}
